name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Actualizado a la última versión

      - name: Use Node.js
        uses: actions/setup-node@v3  # Actualizado a la última versión
        with:
          node-version: '18'  # Actualizado a la versión más reciente de LTS

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.7.2  # Actualizado a la última versión
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3  # Actualizado a la última versión

      - name: Use Node.js
        uses: actions/setup-node@v3  # Actualizado a la última versión
        with:
          node-version: '18'  # Actualizado a la versión más reciente de LTS

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
